name: Golang On Linux

on: [push]

jobs:
  golang_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Build binary
      run: go build -o myapp

    - name: Checkout the samples-go repository
      uses: actions/checkout@v2
      with:
        repository: keploy/samples-go
        path: ./samples-go

    - name: Run samples-go application
      run: |
        cd samples-go/gin-mongo
        chmod +x ./../../.github/workflows/test_workflow_scripts/golang-linux.sh
        ./../../.github/workflows/test_workflow_scripts/golang-linux.sh
