name: Golang On Linux

on: [push]

jobs:
  golang_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Clone Keploy repository
      run: git clone https://github.com/keploy/keploy.git

    - name: Build Keploy from source
      run: |
        cd keploy
        go build -o keploy
      env:
        GO111MODULE: on

    - name: Move Keploy binary to accessible location
      run: sudo mv ./keploy/keploy /usr/local/bin

    - name: Verify Keploy installation
      run: keploy

    - name: Run shell script for application setup and testing
      run: |
        chmod +x ./.github/workflows/test_workflow_scripts/golang-linux.sh
        ./.github/workflows/test_workflow_scripts/golang-linux.sh
